### ISSUE TITLE
Linking errors while compiling against static libraries on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by olegded** [vsg-dev/vsgXchange#10]
Hi Robert,

I have tried to build vsgXchange against default static `glslang` libraries installed via native package manager on Ubuntu 20.04 LTS. It looks like that this Ubuntu version includes latest `glslang` version including [breaking changes as described here](https://github.com/KhronosGroup/glslang/pull/2277), see deletion of `glslang/Include/revision.h`.

Somewhat easy change is to fix [<glslang/Include/revision.h> include here](https://github.com/vsg-dev/vsgXchange/blob/master/src/glsl/ResourceLimits.cpp#L41), although it requires changes to ["#if GLSLANG_PATCH_LEVEL > 3727" test](https://github.com/vsg-dev/vsgXchange/blob/master/src/glsl/ResourceLimits.cpp#L139-L141) to make it right.

However, what I really failed so far is to link against the static libraries resulting in tons of linker errors. I have tried to change [add_library(glslang::glslang UNKNOWN IMPORTED)](https://github.com/vsg-dev/vsgXchange/blob/master/src/glslangConfig.cmake#L147) to `add_library(glslang::glslang STATIC IMPORTED)` (and all subsequent libraries further in the CMake file), still no success. I couldn't figure out whether `set_target_properties` calls need some changes or not, at least I cannot find which flags would be required here.

Latest self-compiled [glslang master branch](https://github.com/KhronosGroup/glslang) using dynamic libraries works. This issue can be reproduced by compiling latest `glslang` master as static libraries under Ubuntu 20.04 LTS.

Do you have an idea what might be missing?

Regards,
Oleg

**Comment by robertosfield** [comment]
Hi Oleg,

On Wed, 2 Sep 2020 at 22:58, olegded <notifications@github.com> wrote:

> I have tried to build vsgXchange against default static glslang libraries
> installed via native package manager on Ubuntu 20.04 LTS. It looks like
> that this Ubuntu version includes latest glslang version including breaking
> changes as described here
> <https://github.com/KhronosGroup/glslang/pull/2277>, see deletion of
> glslang/Include/revision.h.
>
> Somewhat easy change is to fix <glslang/Include/revision.h> include here
> <https://github.com/vsg-dev/vsgXchange/blob/master/src/glsl/ResourceLimits.cpp#L41>,
> although it requires changes "#if GLSLANG_PATCH_LEVEL > 3727" test
> <https://github.com/vsg-dev/vsgXchange/blob/master/src/glsl/ResourceLimits.cpp#L139-L141>
> to make it right.
>
> However, what I really failed so far is to link against the static
> libraries resulting in tons of linker errors. I have tried to change add_library(glslang::glslang
> UNKNOWN IMPORTED)
> <https://github.com/vsg-dev/vsgXchange/blob/master/src/glslangConfig.cmake#L147>
> to add_library(glslang::glslang STATIC IMPORTED) (and all subsequent
> libraries further in the CMake file), still no success. I couldn't figure
> out whether set_target_properties calls need some changes or not, at
> least I cannot find which flags would be required here.
>
> Latest self-compiled glslang master branch
> <https://github.com/KhronosGroup/glslang> using dynamic libraries works.
>
> Do you have an idea what might be missing?
>
I don't know what is missing.  I'll try it first hand today as I now have a
Kubuntu 20.04 install as a dual boot on my dev system, I have it building
against VulkanSDK but that doesn't help recreate the issue you are seeing.

What were the package names you used of glslang and vulkan?

One thing I'm considering is to see how easy it would be to make glslang a
submodule which is built locally.

Robert.

**Comment by olegded** [comment]
- Vulkan SDK is at `1.2.148.0`, updated as described here [Ubuntu packages](https://vulkan.lunarg.com/sdk/home#linux) - `libvulkan1`/`libvulkan-dev`, `lunarg` and `vulkan*` packages

- `glslang-dev`, `glslang-tools`, v8.13.3743+193-1ubuntu20.04-2

I guess using VulkanSDK could break things too when they update to the latest version (at least the breaking change).

Really wondering if there any difference between installing the VulkanSDK via tarball or provided Ubuntu packages. Ubuntu packages look like easier to update via system tools.

**Comment by robertosfield** [comment]
Hi Oleg,

On Thu, 3 Sep 2020 at 09:26, olegded <notifications@github.com> wrote:

>
>    -
>
>    Vulkan SDK is at 1.2.148.0, updated as described here Ubuntu packages
>    <https://vulkan.lunarg.com/sdk/home#linux> - libvulkan1/libvulkan-dev,
>    lunarg and vulkan* packages
>    -
>
>    glslang-dev, glslang-tools, v8.13.3743+193-1ubuntu20.04-2
>
>
I've moved across to Kubuntu 20.04, remove VulkanSDK from my search path,
installed all the above and VSG, vsgXchange & vsgExamples all builds and
link cleanly,

The only problem I had was when I didn't install glslang-tools and
vsgXchange couldn't find the SPIRV-Tools libs and build and attempted a
link anyway, which suggest these are now required libs rather than options.

So are you still getting compile errors with VSG, vsgXchange & vsgExamples
master and the above installed libvulkan-dev, glslang-dev and glslang-tools?

**Comment by olegded** [comment]
Yes and definitely don't have `glslang/Include/revision.h` resulting in a compiler error. I would say having a self-compiled version with dynamic libraries is a working solution/workaround. Maybe it's worth to add an install readme file describing how to install known working version of the `glslang` library.

**Comment by robertosfield** [comment]
Hi Oleg,

On Thu, 3 Sep 2020 at 13:40, olegded <notifications@github.com> wrote:

> Yes and definitely don't have glslang/Include/revision.h resulting in a
> compiler error.
>
Curious.  My install did have this header - my system compiled without any
changes.  I wonder if ubuntu has issued a patch for this.

> I would say having a self-compiled version with dynamic libraries is a
> working solution/workaround. Maybe it's worth to add an install readme file
> describing how to install known working version of the glslang library.
>
I'm currently looking at the glslang repository on github.  They look to
have a bit of lets break 3rd party code spree, indicative of projects more
focused on runtimes rather than focused on 3rd parties linking the libs to
do shader compilation/validation.

I haven't figured out a route through this mess with glslang shifting the
goal posts in ways that make it hard to keep code compiling against newer
and older versions of glslang.  I will look at the practicality of just
checking out and building glslang locally.  If the VSSG/vsgXchange is built
statically then it'd make sense to link glslang statically as well, and
match the dynamic build if this is used as well.

I'd much rather be working on developing the VSG itself rather than trying
to figure out how to cope with libs like glslang breaking code.  Reminds me
of the problems working with ffmpeg and Apple over the years...

Robert.

**Comment by olegded** [comment]
Hi Robert,

I can confirm that both `vsgExamples` and `MyFirstVsgApplication` can be built on Ubuntu 20.04 using latest self-compiled `glslang` master (compiled as a static libraries).

Oleg
